---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster
  region: sa-east-1
availabilityZones: 
- sa-east-1a
- sa-east-1b
managedNodeGroups:
- name: on-demand
  labels:
    role: on-demand
  instanceType: t2.small
  desiredCapacity: 1
  volumeSize: 20