---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awseks
  namespace: staging
  labels:
    app: awseks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: awseks
  template:
    metadata:
      labels:
        app: awseks
    spec:
      containers:
      - name: awseks
        image: 395893388747.dkr.ecr.sa-east-1.amazonaws.com/awseks:latest
        imagePullPolicy: "Never"
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 300m
---
apiVersion: v1
kind: Service
metadata:
  name: awseks
  namespace: staging
spec:
  type: LoadBalancer
  selector:
    app: awseks
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8081
      # Port to forward to inside the pod
      targetPort: 8080